### ISSUE TITLE
Any example of log4j.properties format?

### ISSUE THREAD

**Issue by cacedo** [Graylog2/log4j2-gelf#10] opened 2015-10-01 15:00 UTC
This is what I tried:
log4j.appender.graylog2=org.graylog2.log4j2.GelfAppender
log4j.appender.graylog2.server=mygreylogserver
log4j.appender.graylog2.hostName=myhost

But this is what I get: 
java.lang.ClassNotFoundException: org.graylog2.log4j2.GelfAppender

**Comment by joschi** [comment] 2015-10-01 15:29
This sounds like the appender isn't on the class path. Did you add log4j2-gelf to your classpath, e. g. by adding it to your build as a dependency?

**Comment by CarpathianUA** [comment] 2016-06-30 15:36
@joschi , It would be great if you can provide some example for log4j.properties format

**Comment by joschi** [comment] 2016-07-01 09:53
@CarpathianUA Please refer to https://logging.apache.org/log4j/2.x/manual/configuration.html#Properties for instructions for how to build a log4j 2 configuration from properties files.

I'm closing this issue since the original author didn't reply since October 2015.

**Closed as completed by joschi** 2016-07-01 09:53 UTC
Labels: question

**Comment by rmetzger** [comment] 2016-12-09 20:21
I spend 2 hours figuring out a similar issue, so I thought I'm sharing my fix here.
The problem is that you did not specify the "search package name" at the top of the file like this:
```properties
packages=org.graylog2.log4j2
```

An example of a properties-based log4j2 config with Graylog:
```properties
# set log level for the logger itself (for ex when parsing this file)
status = info
name=PropertiesConfig
# probably irrelevant
property.filename = logs
appenders = console, file, graylog
# define search space for plugins
packages=org.graylog2.log4j2

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{4} - %msg%n

appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName=${sys:log.file}
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{4} - %msg%n


appender.graylog.type=GELF
appender.graylog.name=GRAYLOG
appender.graylog.server=yourhost
appender.graylog.includeStackTrace=true
appender.graylog.additionalFields.type = KeyValuePair
appender.graylog.additionalFields.key=yarncontainer
appender.graylog.additionalFields.value=${env:CONTAINER_ID}


rootLogger.level = debug
#rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRefs = file, graylog
rootLogger.appenderRef.file.ref = LOGFILE
rootLogger.appenderRef.graylog.ref = GRAYLOG
```
